# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
sudo: required
dist: bionic
before_install:
  - git submodule update --init --recursive
install:
  - sudo apt-get update -qy; sudo apt-get install -qy python-dev python3-dev python3.7-dev
script:
  - cmake -H. -Bbuild && cmake --build build -- -j 4 && echo Testing && bin/odgi test && cd lib && ls -l && python3.7 -c 'import odgi; g = odgi.graph()'
