on: [ push ]

name: build and test

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y
          git
          bash
          cmake
          make
          g++
          python3-dev
          python3-distutils
          autoconf
          build-essential
          libjemalloc-dev
      - name: Init and update submodules
        run: git submodule update --init --recursive
      - name: Build odgi
        run: sed -i 's/CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS} -O3 -mcx16 -g/CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O -mcx16 -g -fsanitize=address/g' CMakeLists.txt && sed -i 's/CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS} -O3 -mcx16 -g/CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O -mcx16 -g -fsanitize=address/g' CMakeLists.txt && cmake -H. -Bbuild && cmake --build build -- -j 2
      - name: Run odgi tests
        run: ASAN_OPTIONS=detect_leaks=1:symbolize=1 LSAN_OPTIONS=verbosity=0:log_threads=1 bin/odgi test
        # https://stackoverflow.com/questions/59853730/asan-issue-with-asan-library-loading
        # https://gitmemory.com/issue/diasurgical/devilutionX/183/511474901
      - name: Disable ASan sanity checking
        run: sudo rm -f /etc/ld.so.preload && sudo echo '/usr/lib/x86_64-linux-gnu/libasan.so.5.0.0' > /etc/ld.so.preload && export ASAN_OPTIONS=verify_asan_link_order=0 && export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.5.0.0
      - name: Test python import
        run: cd lib && ls -l && python3.8 -c 'import odgi; g = odgi.graph()'
